package com.leptonmaps.wirelinefeasibility.enums;

/**
 * Created by Hardik bansal on 02/06/2017.
 */

public enum APIType {
    LOGIN,
    GET_TOWERS, REVERSE_GEO_CODE, GET_SERVICE_TYPE, GET_COST, SAVE_FEASIBILE_DATA, GET_CIRCLE_TYPE, GET_SUMMARY_COUNT, GET_SUMMARY, GET_SEGMENT_TYPE, GET_CWW_LOCATION, GET_DC_LOCATION, GET_LOCATION_END,GET_DP,GET_DIRECTIONS,GET_WIRE_TYPE,GET_SPEED_VALUES;

}